spring:
  application:
    name: Lumi-Backend
  profiles:
    active: dev

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    mail:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

app:
  frontend:
    url: ${FRONTEND_URL}
  reset-password-url: ${URL_RESET_PASSWORD}
  resend:
    api-key: ${RESEND_API_KEY}
  email:
    from: ${EMAIL_FROM:onboarding@resend.dev}

URL_CORS: ${URL_CORS}

abacatepay:
  api:
    key: ${ABACATE_PAY_API_KEY}
  webhook:
    secret: ${ABACATE_PAY_WEBHOOK_SECRET}
